""" This may just need to be a text file not a py file.
The purpose is to collect the NetX360 Client Onboarding (COB)
Fields that need review. The Excel output is terrible, so this would
translate it. Probably in a dictionary structure.
"""
# TODO: read in the list of required field.
#       look up answers I already know (cache)
#       ask for the ones I don't, and save the answers to the cache
#       json sounds right for that.



some_fields = {
    'PRIMARY ACCOUNT HOLDER - EMPLOYMENT INFO - BUSINESS TYPE IS MANDATORY': '',
    'PRIMARY ACCOUNT HOLDER - EMPLOYMENT INFO - ADDITIONAL EMPLOYMENT INFO - EMPLOYER ADDRESS - ADDRESS LINE 1 IS MANDATORY': '',
    'PRIMARY ACCOUNT HOLDER - EMPLOYMENT INFO - ADDITIONAL EMPLOYMENT INFO - EMPLOYER ADDRESS - CITY IS MANDATORY': '',
    'PRIMARY ACCOUNT HOLDER - EMPLOYMENT INFO - ADDITIONAL EMPLOYMENT INFO - EMPLOYER ADDRESS - STATE / PROVINCE IS MANDATORY': '',
    'PRIMARY ACCOUNT HOLDER - EMPLOYMENT INFO - ADDITIONAL EMPLOYMENT INFO - EMPLOYER ADDRESS - ZIP / POSTAL CODE IS MANDATORY': '',
    'PRIMARY ACCOUNT HOLDER - INVESTMENT KNOWLEDGE AND EXPERIENCE - GENERAL INVESTMENT KNOWLEDGE IS MANDATORY': '',
    'PRIMARY ACCOUNT HOLDER - INVESTMENT KNOWLEDGE AND EXPERIENCE - INVESTMENT KNOWLEDGE - INVESTMENT KNOWLEDGE IS MANDATORY': '',
    'PRIMARY ACCOUNT HOLDER - INVESTMENT KNOWLEDGE AND EXPERIENCE - INVESTMENT KNOWLEDGE - INVESTMENT KNOWLEDGE IS MANDATORY': '',
    'PRIMARY ACCOUNT HOLDER - INVESTMENT KNOWLEDGE AND EXPERIENCE - INVESTMENT KNOWLEDGE - INVESTMENT KNOWLEDGE IS MANDATORY': '',
    'PRIMARY ACCOUNT HOLDER - INVESTMENT KNOWLEDGE AND EXPERIENCE - INVESTMENT KNOWLEDGE - INVESTMENT KNOWLEDGE IS MANDATORY': '',
    'PRIMARY ACCOUNT HOLDER - INVESTMENT KNOWLEDGE AND EXPERIENCE - INVESTMENT KNOWLEDGE - INVESTMENT KNOWLEDGE IS MANDATORY': '',
    'PRIMARY ACCOUNT HOLDER - INVESTMENT KNOWLEDGE AND EXPERIENCE - INVESTMENT KNOWLEDGE - INVESTMENT KNOWLEDGE IS MANDATORY': '',
    'PRIMARY ACCOUNT HOLDER - INVESTMENT KNOWLEDGE AND EXPERIENCE - INVESTMENT KNOWLEDGE - INVESTMENT KNOWLEDGE IS MANDATORY': '',
    'PRIMARY ACCOUNT HOLDER - INVESTMENT KNOWLEDGE AND EXPERIENCE - INVESTMENT KNOWLEDGE - INVESTMENT KNOWLEDGE IS MANDATORY': '',
    'PRIMARY ACCOUNT HOLDER - INVESTMENT KNOWLEDGE AND EXPERIENCE - INVESTMENT KNOWLEDGE - INVESTMENT KNOWLEDGE IS MANDATORY': '',
    'PRIMARY ACCOUNT HOLDER - INVESTMENT KNOWLEDGE AND EXPERIENCE - INVESTMENT KNOWLEDGE - INVESTMENT KNOWLEDGE IS MANDATORY': '',
    'PRIMARY ACCOUNT HOLDER - INVESTMENT KNOWLEDGE AND EXPERIENCE - INVESTMENT KNOWLEDGE - INVESTMENT KNOWLEDGE IS MANDATORY': '',
    'PRIMARY ACCOUNT HOLDER - INVESTMENT KNOWLEDGE AND EXPERIENCE - INVESTMENT KNOWLEDGE - INVESTMENT KNOWLEDGE IS MANDATORY': '',
    'PRIMARY ACCOUNT HOLDER - BROKER-DEALER AFFILIATIONS - RELATED TO AN EMPLOYEE OF THIS BROKER-DEALER? IS MANDATORY': '',
    'PRIMARY ACCOUNT HOLDER - BROKER-DEALER AFFILIATIONS - RELATED TO AN EMPLOYEE OF ANOTHER BROKER-DEALER? IS MANDATORY': '',
    'PRIMARY ACCOUNT HOLDER - BROKER-DEALER AFFILIATIONS - MAINTAINING OTHER BROKERAGE ACCOUNTS IS MANDATORY': '',
    'PRIMARY BENEFICIARY 1 - NAME DETAILS - RELATIONSHIP IS MANDATORY': '',
    'PRIMARY BENEFICIARY 1 - NAME DETAILS - FIRST NAME IS MANDATORY': '',
    'PRIMARY BENEFICIARY 1 - NAME DETAILS - LAST NAME IS MANDATORY': '',
    'PRIMARY BENEFICIARY 1 - DATE OF BIRTH IS MANDATORY': '',
    'PRIMARY BENEFICIARY 1 - GENDER IS MANDATORY': '',
    }

